### ISSUE TITLE
Investigate next.js server side caching for performance improvement

### ISSUE THREAD

**Issue by mika018** [voluntree-uk/app-next#12]
See what options next.js has for this and whether we can use it in a meaningful way.

**Comment by alexomon018** [comment]
There is a cool blog (https://web.dev/stale-while-revalidate/) about this, but to cut long story short we can use caching headers in getServerSideProps like this:

res.setHeader('Cache-Control', 'value_you_prefer') 

By default, Cache-Control headers will be set differently depending on how your page fetches data.
If the page uses getServerSideProps or getInitialProps, it will use the default Cache-Control header set by next start in order to prevent accidental caching of responses that cannot be cached. 

There is also a topic about this in next Docs (https://nextjs.org/docs/going-to-production)
