### ISSUE TITLE
Correct BookingDetails query & interface

### ISSUE THREAD

**Issue by harryndavies** [voluntree-uk/app-next#18]
Only one workshop and slot will be returned per booking, so property names should be singular (workshop and slot inside the select are aliases). 

Also, it's worth noting that we are only returning a few properties, and not the complete interface. Might be worth just returning the complete workshop and slot data for now to avoid issues with trying to access properties that don't exist? 

**Query should read**

```
const { data: bookings } = await supabase
    .from("bookings")
    .select(`
      *,
      workshop:workshop_id(name),
      slot:slot_id(date, start_time, end_time)
    `)
    .eq("user_id", user?.id);
```

**Interface should read** 

```
export interface BookingDetails extends Booking {
  workshop: Workshop;
  slot: Slot;
}
```

**Comment by mika018** [comment]
I don't think that this is possible as those are table references. 
It will only work if we rename tables to be singular as well.

**Comment by mika018** [comment]
Makes sense to do this sooner rather than later. Definitely don't want to do it after the release.

Just need to track all the places where the change needs to happen:
- [ ] rename supabase tables from plural to singular
- [ ] update all the supabase queries in code to reflect name change
- [ ] update interfaces to reflect name change
- [ ] update all remote procedure calls ([RPCs](https://github.com/voluntree-uk/app-next/wiki/Database-Schema#postgres-remote-procedure-calls)) 
- [ ] test run the whole system to make sure it is working correctly
- [ ] document changes to table names, RPCs and row level security policies in the [Database Schema](https://github.com/voluntree-uk/app-next/wiki/Database-Schema) doc
